### PR TITLE
Fix for Transparency

### PR DESCRIPTION
**Pull request by JaduBen**
Hooks up the Color alpha to transparency. This allows for modifying the object transparency through the Color slider.

### CODE REVIEW

**Comment by WojciechSwierczykPTC** [comment]
This pull request breaks URP shaders. JSONs in shadergraph files are corrupted. They have more than one root element. To reproduce you just need to launch any project with GLTFUtility and import errors will come out in unity output window.

**Comment by JaduBen** [comment]
Can you attach a screenshot of this? I am looking at it in a project now and it seems to be ok.
image

**Comment by WojciechSwierczykPTC** [comment]
Simple test. I took Standard (Metallic).shadergraph file from latest master commit, copied content of it and pasted it to https://jsonformatter.curiousconcept.com
This is the result:
image

**Comment by JaduBen** [comment]
I'm not sure that is a bug. While a third party json formatter may not like it, this appears to be the format the Unity understands. Try opening the shader in Unitys shader graph.

**Comment by Siccity** [comment]
Maybe it's a Unity version thing. Which Unity versions are you both on?

**Comment by JaduBen** [comment]
2020.3.22f1

**Comment by WojciechSwierczykPTC** [comment]
My Unity is saying the same as third party validators and can't even read it as a proper shader. 2019.4.10f1.
image

**Pull request merged**
