### PR TITLE
Adapt to draco 4.0.2 (Fix WebGL build for Unity 2021 and 2022)

### PR DESCRIPTION
**Pull request by rasoulMrz**
As mentioned in issue #169, we have to use Draco version 4.x.x, in order to fix WebGL, builds on Unity 2021 and 2022. But it is also mentioned in the issue that if you simply remove the current version and install Draco 4.0.2 (e.x. using the [installer](https://package-installer.glitch.me/v1/installer/OpenUPM/com.atteneder.draco?registry=https%3A%2F%2Fpackage.openupm.com&scope=com.atteneder) provided in the [GitHub repo](https://github.com/atteneder/DracoUnity)) you will encounter build errors as the GLTFUtility is using methods with old signature. In order to fix this, you have to adapt the `GLTFUtilityDracoLoader.cs` to the new Draco API.

This pull request contains the adapted version of `GLTFUtilityDracoLoader.cs` and the old Draco plugin is also deleted from sources (you will need to install the new version as mentioned above).

### CODE REVIEW

**Comment by saszer** [comment]
image
Throws this error while trying to load the build on WebGL

**Comment by saszer** [comment]
Works well, hoping for a merge.

**Comment by EnigmaFactory** [comment]
This works great! Think this should get merged.

**Comment by JCMazza** [comment]
This does not work for me and still get the errors for webgl build

**Pull request merged**
