### PR TITLE
Implement BlendShape Animation with keyframe compression, Stepped and Linear Interpolation Modes, Custom framerate for imported animation clips, and package dependencies.

### PR DESCRIPTION
**Pull request by diegodelarocha**
@sprylyltd and I have been adding some features to your wonderful utility 💜, and we hope you find these helpful to integrate on yours too 🧠:

- Animate blend shapes.

> Implements a way to add Blend Shapes/Key Shapes authored in blender, and bring them in as animation clips, which is very useful for animation, such as adding corrective blend shapes, or doing blend shape driven animation.

- Animate with stepped and linear interpolation modes.

> Imports animation with interpolation as close as possible as it was in blender (a fix for non - interpolated animation to work properly on Unity).

- Force animations to use a specific interpolation mode.

> Options to force all keyframes to be a specific interpolation mode _ie all keys set to constant, to show blocking work_

- Cut out redundant blend shape animation key frames.

> When importing blend shapes, it created a lot of garbage frames, so this feature, helps compress those animation clips, and lets us keep only the necessary keyframes 🤓.

- Set a custom frame rate on imported animation clips.

> Lets user pick a frame rate on import, which gives the ability to stay consistent to whatever frame rate we used to author the animation in Blender.

- Don't worry about installing package dependencies.

> Json dependency is included on the package

Here's a screenshot of some of the features added on the Editor:

Screen Shot 2020-05-06 at 9 59 26 AM

### CODE REVIEW

**Comment by Siccity** [comment]
Whoah, nice job guys!
I can't merge this PR for several reasons, but I'll look through your changes and see what I can use in the following days :)

**Comment by diegodelarocha** [comment]
Thanks @Siccity 💜🙏 Yes of course, looking forward to see what gets implemented 😍 
Let me know if we can help in any way 💛🧠

**Comment by diegodelarocha** [comment]
I think it makes sense that .gltf animation clips are tied to seconds to get all the precision needed depending on where it's going to be used, and I understand that for programming purposes it's the preferred method, and I agree it should be the base of it 🤓.

Thaaaat said, when importing in Unity, it will bring it in as an animation clip that just assumes it's `60 FPS` regardless of what FPS was authored with on Blender (I imagine, because it's ignoring the FPS scale, and just making sure the timeScale works). And it's also understandable that it's assuming 60FPS since a lot of interactive media is based on that FPS, and it's closer to the seconds scale, and it only cares about the seconds.

All of that I agree with, when it becomes an issue, is when in practice as animators we do use the FPS scale more than seconds used with programmers, mostly because of legacy of film, and it's what all our language has been based off for almost 100 years, so even though some of us can make the math to change it, in practice a lot of classically trained people that could bring some amazing work in, just understand frames per second. 

We author our work on a different frame rate on Blender, be it (24, 30, 60, etc), when it imports in Unity it still assumes the frame rate is 60 FPS, it _does_ play at the right intervals as in Blender, because it likely is using the seconds to get the right playtime, but it just gets very confusing for the user that might require to do any changes in engine, if the frame rate is different it just makes it very confusing and complicated to work with.

I'm adding an example where the asset was authored at 24 FPS in blender, and on the imported animation clip it assumes the Frame Rate is "60FPS" and it does show the right timing on play back on the animation clip that assumes its 60 FPS (even though it was authored at 24 FPS). And if you duplicate the clip, and change the samples manually to 24 FPS so that we can make edits on the authored frame rate, it just scales the time to slower and wrong playback, so the actual asset that we'd have to use is the one that says its 60 fps, and if we need to do some animation changes, or calls at a specific frame of it, we are blind as in what frame, millisecond we need to do the change, because the scale is already assumed wrong. 

I know it might not be the cleanest direct path, but maybe there's a way to give an `option` to users whether they just want it to use/assume the timeScale as default, but if we need or require the FPS scale, it would be super helpful for users that live with this every day?

Or maybe I'm not understanding the timeScale sugestion properly? 🤓 would that solve the issue on the video I'm attaching? 😍 

https://vimeo.com/416001059/7ff8b9bc50

**Comment by Siccity** [comment]
I dont think GLTF supports FPS in animations at all. The sampler input values are seconds, not frames. This means it shouldn't matter what you set your fps setting to in blender, it should come out correctly in Unity if the exporter does the conversion right. If you have an example of a model that imports incorrectly I'd like to see it, both the .blend and the GLTF file. I created an issue on the official GLTF repo to get some clarification. https://github.com/KhronosGroup/glTF/issues/1811

**Comment by Siccity** [comment]
Additionally, on the interpolationMode.Step, you added some editor-only code. I did a quick test and it seemed like setting the tangents to float.PositiveInfinity correctly parsed as step keyframes. Is there any problem with this? What's the editor code for?

**Comment by diegodelarocha** [comment]
_*Disclaimer: My friend @bdjones is the person who made all this code. He programs 🧠, I've mostly been providing the examples and requirements, so my knowledge is limited, but I will do my best to help 🙏🤓*_

>I dont think GLTF supports FPS in animations at all. The sampler input values are seconds, not frames. This means it shouldn't matter what you set your fps setting to in blender, it should come out correctly in Unity if the exporter does the conversion right. If you have an example of a model that imports incorrectly I'd like to see it, both the .blend and the GLTF file. I created an issue on the official GLTF repo to get some clarification. KhronosGroup/glTF#1811

Interesting! Thanks for making that issue on the GLTF repo 🙏. That's understandable that time scale is the most reliable for all the case scenarios 🤓, I do wonder if there's a way to have it as an option almost like a helper of some sort for this importer?

Also, In Unity the video I sent you before the Sampler input value I was using was `Frames`, it's quite hidden on the UI, but there's a little button on the right side on the most current versions of Unity (I'm on 2019.3.2f1), they likely added this to address the need for having this frame scale as an option. That's where it shows/assumes at import that the frame rate is at `60fps`.... If GLTF itself doesn't support FPS animation, is there a way to have an option to ask the user at import to plug in our our desired FPS, since likely the user will know at what it was authored at, that way it imports with the desired FPS? 🤓 it could have a default of `60FPS`, but have the option to change it?

Samples in FPS


--------------------

> Additionally, on the interpolationMode.Step, you added some editor-only code. I did a quick test and it seemed like setting the tangents to float.PositiveInfinity correctly parsed as step keyframes. Is there any problem with this? What's the editor code for?

I do remember @bdjones trying to set step tangents directly on the API without using Editor-only code (maybe exactly the same setting you're trying?) But I recall him having a bunch of issues with the rotations, I think it was something to do with the translation of Euler, and Quaternions conversions from Blender to Unity wasn't loving it? I don't know exactly but it was just breaking the rotation poses a lot to the point that they were not usable. 

I'll attach some examples for you to test, and If it works with your solution and its cleaner without editor-code only, even better 🤓💜 Crossing my fingers 🤞, but let me know if you need any further test examples/scenes.

--------------------

>If you have an example of a model that imports incorrectly I'd like to see it, both the .blend and the GLTF file.

I'm attaching two examples for you to play with, `cactus` has both bone animation and blend shapes and they work on the fork we made, that's what we were using to test/make the changes on the importer.

-  In this test, you can try to manually/by code set the keys of `idle` to constant, and it breaks the rotation and interpolation on the eyes, or anywhere else it requires rotation. I think that's why @bdjones decided to use the in editor hack. Maybe there's a simpler/cleaner solution that we just didn't find? 🤓
-  It also includes blend shapes animation, it will load on our forked version :)


And `sumo` is the one I used to send you that video, unfortunately that one I haven't found the blender file yet, but adding it just in case. Let me know if you need any other test, and I'm happy to provide 🤓.

[SteppedAnimationBlendshapesFPStest.zip](https://github.com/Siccity/GLTFUtility/files/4600599/SteppedAnimationBlendshapesFPStest.zip)

**Comment by diegodelarocha** [comment]
Just heardback from @bdjones on this 🤓:

> "This [old post](https://forum.unity.com/threads/new-animationclip-property-names.367288/#post-2384172) from a Unity dev has a lot of the context:
> 
> >" Changing any of those editor curves (through AnimationUtility.SetEditorCurve) will cause changes in the underlying curves to which they map, and changing the underlying curves (through AnimationClip.SetCurve) will cause changes to those curves. "
> 
> Unity has several different properties that can all affect rotation, but not all of them can be modified at runtime. And I thiiiiiiiink the reason why I needed to pull the editor code in is because someone -- either Unity or Blender (or both... I can't remember 😅) -- was setting rotation data on curves that can only be edited by the editor API. Without it, it would do some weird interpolation around each keyframe that was not intended.
> 
> 
> BUT!! I'm POSITIVE Siccity has a better grasp on the code than I do 😄 I was taking stabs in the dark"

Hopefully this is helpful? 🤓 <3

**Comment by ozgurozansen** [comment]
Great work here! Blend shapes animation support is definitely the one we are looking for.. Is merging to master branch still in progress?

**Comment by ruifigueiredo19** [comment]
Any updates on this feature?

**Comment by Siccity** [comment]
> Any updates on this feature?

Yes, blend shapes have already been added to the main branch. As stated earlier, this PR will not get merged, but I'm keeping it open for reference.

**Comment by ruifigueiredo19** [comment]
> Yes, blend shapes have already been added to the main branch. 

Blendshapes are imported properly. However, as per the current version in [master](https://github.com/Siccity/GLTFUtility/blob/703b0043e85193a4eb5632d882a5ce39495be2d2/Scripts/Spec/GLTFAnimation.cs#L142) there is no support for importing animations with morph/blendshape weights (which was one of the goals of this PR)

**Pull request closed without merging**
